config/routes.rb
Rails.application.routes.draw do
  get '/' => 'books#index'

  devise_for :admin, skip: [:passwords, :registrations], controllers: { sessions: 'admin/sessions' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '/:locale' do
    root 'books#index'

    devise_for :users, controllers: {
                         confirmations: 'users/confirmations',
                         passwords: 'users/passwords',
                         registrations: 'users/registrations'
                     }, skip: :omniauth_callbacks

    get 'my_books', to: 'books#my_books', as: :my_books

    resources :books do
      resources :comments, except: [:index, :show], shallow: true
      post 'evaluate', to: 'evaluations#evaluate'
    end
    get 'change_locale' => 'locales#change_locale'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :text, :book_id, :user_id, presence: true
  default_scope -> { order('created_at DESC') }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_book, only: [:new, :create]
  before_action :find_comment, only: [:edit, :update, :destroy]

  def new
    @comment = current_user.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.book_id = @book.id
    @new_comment = Comment.new

    respond_to do |format|
      if @comment.save
        format.html { redirect_to book_path(@book) }
        format.js
      else
        format.html { render 'new' }
        format.js { render 'not_created' }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to book_path(@comment.book) }
        format.js
      else
        format.html { render 'edit' }
        format.js { render 'not_updated' }
      end
    end
  end

  def destroy
    book = @comment.book
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to book_path(book) }
      format.js { render json: true }
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:text)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

    def find_comment
      @comment = current_user.comments.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" data-id="<%= comment.id %>">
  <div class="comment-section">
    <div class="comment-owner">
      <%= link_to comment.user.name, "#" %>
    </div>

    <p><%= comment.text %></p>

    <% if current_user == comment.user %>
      <div class="comment-links">
        <%= link_to t('edit'), edit_comment_path(comment), data: { id: comment.id, remote: true } %>
        <%= link_to t('delete'), comment_path(comment), method: :delete, data: { confirm: t('are_you_sure?'), remote: true } %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@book, @comment] do |f| %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

app/views/comments/_remote_form.html.erb
<%= simple_form_for [@book, comment], remote: true do |f| %>
  <%= f.input :text %>
  <%= f.button :submit %>
  <% unless comment.new_record? %>
    <a class="btn btn-default" data-cancel-comment-editing><%= t('cancel') %></a>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("<%= escape_javascript(render @comment) %>").prependTo("#comments");
$('#comment-form').html(
  $("<%= escape_javascript(render 'remote_form', comment: @new_comment) %>")
)

app/views/comments/edit.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
  <div class="block">
    <h3 class="text-center"><%= t('edit_comment_title') %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/comments/edit.js.erb
$('<%= ".comment[data-id=#{@comment.id}]" %>').append(
  $("<%= escape_javascript(render 'remote_form', comment: @comment) %>")
).children('.comment-section').hide();

app/views/comments/new.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
  <div class="block">
    <h3 class="text-center"><%= t('new_comment_title') %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/comments/not_created.js.erb
$('#comment-form').html(
  $("<%= escape_javascript(render 'remote_form', comment: @comment) %>")
)

app/views/comments/not_updated.js.erb
$('<%= ".comment[data-id=#{@comment.id}] form" %>').replaceWith(
  $("<%= escape_javascript(render 'remote_form', comment: @comment) %>")
);

app/views/comments/update.js.erb
$('<%= ".comment[data-id=#{@comment.id}]" %>').replaceWith(
  $("<%= escape_javascript(render 'comment', comment: @comment) %>")
);