config/routes.rb
Rails.application.routes.draw do
  get '/' => 'books#index'

  devise_for :admin, skip: [:passwords, :registrations], controllers: { sessions: 'admin/sessions' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '/:locale' do
    root 'books#index'

    devise_for :users, controllers: {
                         confirmations: 'users/confirmations',
                         passwords: 'users/passwords',
                         registrations: 'users/registrations'
                     }, skip: :omniauth_callbacks

    get 'my_books', to: 'books#my_books', as: :my_books

    resources :books do
      resources :comments, except: [:index, :show], shallow: true
      post 'evaluate', to: 'evaluations#evaluate'
    end
    get 'change_locale' => 'locales#change_locale'
  end
end

app/models/book.rb
require 'file_size_validator'

class Book < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments, dependent: :destroy
  has_many :evaluations, dependent: :destroy
  validates :title, :description, :author, :user_id, presence: true
  validates :description, length: { minimum: 50 }
  validates :categories, length: { minimum: 1 }

  mount_uploader :image, BookImageUploader
  validates :image, file_size: { maximum: 1.megabyte.to_i }

  def average_evaluation
    number_of_evaluations = summa_of_evaluations = 0
    self.evaluations.each do |evl|
      summa_of_evaluations += evl.value
      number_of_evaluations += 1
    end
    avg = summa_of_evaluations.to_f / number_of_evaluations
    avg.nan? ? 0 : avg
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_book, only: :show
  before_action :find_book_for_current_user, only: [:edit, :update, :destroy]

  def my_books
    @books = current_user.books.order('created_at DESC')
  end

  def index
    @books = if params[:category].blank?
               Book.order('created_at DESC').page(params[:page]).per(12)
             else
               category = Category.find_by(name: params[:category])
               Book.includes(:categories)
                   .where(categories: { id: category.id })
                   .order('books.created_at DESC')
                   .page(params[:page])
                   .per(12)
             end
  end

  def show
    @comments = @book.comments # => @book.comments.page(params[:page]).per(10)
    @average_book_evaluation = @book.average_evaluation
    @number_of_evaluations = @book.evaluations.count

    if current_user
      @new_comment = Comment.new
      @evaluation = Evaluation.where(book_id: @book.id, user_id: current_user.id).first
    end
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title,  :description,
                                   :author, :image, category_ids: [])
    end

    def find_book
      @book = Book.find(params[:id])
    end

    def find_book_for_current_user
      @book = current_user.books.find(params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="book-image-section super-small col-xs-6 col-sm-4 col-md-4 col-lg-3">
  <%= link_to book_path(book) do %>
    <%= image_tag book.image_url, class: "book" %>
  <% end %>
  <div class="book-title">
    <%= book.title %>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => {:multipart => true} do |f| %>
  <%= f.association :categories %>
  <%= f.input :image, as: :file, input_html: { class: "filestyle" } %>
  <%= f.input :title %>
  <%= f.input :description, input_html: {rows: 5}  %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
  <div class="block">
    <h3 class="text-center"><%= t('edit_book_title') %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/books/index.html.erb
<div class="category-picker">
  <select class="selectpicker" data-live-search="true" title="<%= t('choose_category') %>">
    <% Category.cached_categories.each do |category| %>
      <% if params[:category] == category.name %>
        <option value="<%= books_path(category: category.name) %>" selected="selected">
          <%= category.name %>
        </option>
      <% else %>
        <option value="<%= books_path(category: category.name) %>">
          <%= category.name %>
        </option>
      <% end %>
    <% end %>
  </select>
</div>

<% if @books.any? %>
  <div class="row">
    <%= render @books %>
    <div class="home-page-pagination text-center col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= paginate @books %>
    </div>
  </div>
<% else %>
  <h3><%= t('no_books') %>.</h3>
<% end %>

app/views/books/my_books.html.erb
<h1 id="my_books"><%= t('my_books') %></h1>
<% if @books.any? %>
  <div class="row">
    <%= render @books %>
  </div>
<% else %>
  <h3><%= t('no_my_books') %>.</h3>
<% end %>

app/views/books/new.html.erb
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
  <div class="block">
    <h3 class="text-center"><%= t('new_book_title') %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="book-image-section col-xs-12 col-sm-6 col-md-4 col-lg-4">

    <%= image_tag @book.image_url, class: "book-show" %>

    <div class="btn-section">
      <div class="btn-group">
        <% if @book.user == current_user %>
          <%= link_to t('edit'),   edit_book_path(@book), class: "btn btn-default" %>
          <%= link_to t('delete'), book_path(@book), method: :delete, data: { confirm: t('are_you_sure?') }, class: "btn btn-default" %>
        <% else %>
          <div class='your-evaluation'><%= t('your_evaluation') %></div>
          <span id="evaluation" data-value="<%= @evaluation ? @evaluation.value : 0 %>" data-url="<%= book_evaluate_path(@book) %>"></span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="book-data-section col-xs-12 col-sm-6 col-md-8 col-lg-8">
    <div class="block">
      <h3><%= @book.title %></h3>
      <h4 class="author"><%= @book.author %></h4>
      <div class="average-book-evaluation-section">
        <span id="average-book-evaluation" data-value="<%= @average_book_evaluation %>"></span>
        <span class="number-of-evaluations-section">
          <%= t('number_of_evaluations') %>: <span id="number-of-evaluations"> <%= @number_of_evaluations %></span>
        </span>
      </div>
      <p class="book-description"><%= @book.description %></p>
      <div class="categories">
        <%= render @book.categories %>
      </div>
      <div class="added-by"><%= t('added_by') %> <a href="#"><%= @book.user.name %></a></div>
    </div>

    <!--<div class="btn-section">
      <div class="btn-group">
        <#%= link_to t('add_comment'), new_book_comment_path(@book), class: "btn btn-default" %>
      </div>
    </div>-->
  </div>

  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8" style="float: right;">
    <div class="block">
      <h3 class="text-center"><%= t('comments') %></h3>

      <% if current_user %>
        <div id="comment-form">
          <%= render 'comments/remote_form', comment: @new_comment %>
        </div>
      <% end %>

      <div id="comments">
        <%= render @comments %>
      </div>

      <!--<div class="text-center">
        <#%= paginate @comments, pagination_class: "pagination-sm" %>
      </div>-->
    </div>
  </div>
</div>