config/routes.rb
Rails.application.routes.draw do
  get '/' => 'books#index'

  devise_for :admin, skip: [:passwords, :registrations], controllers: { sessions: 'admin/sessions' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '/:locale' do
    root 'books#index'

    devise_for :users, controllers: {
                         confirmations: 'users/confirmations',
                         passwords: 'users/passwords',
                         registrations: 'users/registrations'
                     }, skip: :omniauth_callbacks

    get 'my_books', to: 'books#my_books', as: :my_books

    resources :books do
      resources :comments, except: [:index, :show], shallow: true
      post 'evaluate', to: 'evaluations#evaluate'
    end
    get 'change_locale' => 'locales#change_locale'
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home Library</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="admin-container">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home Library</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Home Library", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav navbar-keft">
        <li><%= link_to t('add_book'), new_book_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <#%= t('categories') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <#% Category.cached_categories.each do |category| %>
              <li class="<#%= 'active' if params[:category] == category.name %>">
                <#%= link_to category.name, books_path(category: category.name), class: "link" %>
              </li>
            <#% end %>
          </ul>
        </li>
        -->

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= t('language') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% Language.cached_languages.each do |language| %>
              <li class="<%= 'active' if I18n.locale.to_s == language.abbr %>">
                <%= link_to language.name, change_locale_path(language_abbr: language.abbr), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= t('menu') %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('my_books'), my_books_path %></li>
              <li><%= link_to t('sign_out'), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <li><%= link_to current_user.name, edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to t('devise.sessions.new.sign_in'), new_user_session_path %></li>
          <li><%= link_to t('devise.registrations.new.sign_up'), new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash-#{name}", class: "flash" if msg.is_a?(String) %>
    <% end %>

    <%= yield %>
  </div>

  <footer>
    <div class="container">
      <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 footer-link-section">
          <%= link_to t('about'), "#" %>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 footer-link-section">
          <%= link_to t('help'), "#" %>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 footer-link-section">
          <%= link_to t('contacts'), "#" %>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 footer-link-section">
          <%= link_to t('feedback'), "#" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <%= link_to '#', class: 'social-link' do %>
          <%= image_tag "socials/facebook.png", size: "40x40" %>
        <% end %>
        <%= link_to '#', class: 'social-link' do %>
          <%= image_tag "socials/vk.png", size: "40x40" %>
        <% end %>
        <%= link_to '#', class: 'social-link' do %>
          <%= image_tag "socials/twitter.png", size: "40x40" %>
        <% end %>
        <%= link_to '#', class: 'social-link' do %>
          <%= image_tag "socials/youtube.png", size: "40x40" %>
        <% end %>
      </div>
    </div>
  </footer>

</body>
</html>